name: Build binaries and Release for Linux

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
      fail-fast: false

    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: 0
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v7

      - name: Show workflow information
        run: |
          _NAME=$(jq ".[\"$GOOS-$GOARCH\"].friendlyName" -r < .github/build/friendly-filenames.json)
          echo "GOOS: $GOOS, GOARCH: $GOARCH, RELEASE_NAME: $_NAME"
          echo "ASSET_NAME=$_NAME" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Get project dependencies
        run: go mod download

      - name: Build Xray
        run: |
          mkdir -p build_assets
          COMMID=$(git describe --always --dirty)
          echo 'Building Xray...'
          go build -o build_assets/Xray-${{ env.ASSET_NAME }} -trimpath -buildvcs=false -gcflags="all=-l=4" -ldflags="-X github.com/xtls/xray-core/core.build=${COMMID} -s -w -buildid=" -v ./main

      - name: Generate checksums
        if: github.event_name == 'release'
        shell: bash
        run: |
          FILE=./build_assets/Xray-${{ env.ASSET_NAME }}
          DGST=$FILE.dgst
          for METHOD in {"md5","sha1","sha256","sha512"}
          do
            openssl dgst -$METHOD $FILE | sed 's/([^)]*)//g' >>$DGST
          done

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build_assets/Xray-${{ env.ASSET_NAME }}*
          tag: ${{ github.ref }}
          file_glob: true

      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Xray-${{ env.ASSET_NAME }}
          path: |
            ./build_assets/*
